services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=chat
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=chat
    volumes:
      - ./backend/sqls/init:/docker-entrypoint-initdb.d

  backend:
    image: zukidocker/chat-backend:latest
    ports:
      - "1234:1234"
    environment:
      - DB_HOST=db
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_SSLMODE=disable
      - BACKEND_LISTEN_ADDRESS=:1234
    depends_on:
      - db
  
  gateway:
    image: zukidocker/chat-gateway:latest
    ports:
      - "1235:1235"
    environment:
      - BACKEND_LISTEN_ADDRESS=backend:1234